name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello World"

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Définir une variable d'environnement
        env:
          MESSAGE: "Déploiement réussi"
        run: echo "Variable MESSAGE définie"

      
      - name: Afficher la variable
        env:
          MESSAGE: "Déploiement réussi" 
        run: echo "$MESSAGE"
        
      - name: Afficher le secret
        env:
          MY_SECRET: ${{ secrets.API_KEY }}
        run: |
          echo "La valeur du secret est : $MY_SECRET"