name: CI Pipeline

on:
    push:    
        branches:
            - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository # On met a jour notre repo la ou on est
        uses: actions/checkout@v4

      - name: greeting 
        uses: echo "Hello World"

    