name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"


      - name: Set up Node.js # Ici j'installe node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint
